### ISSUE TITLE
wrong usage of assert

### ISSUE THREAD

**Issue by stoeffel** [addyosmani/selectionsort#4]
Some of the tests will never fail, because `assert` is used wrong.
The API of `assert` is: `assert(value, message)` but in the tests it was used like this `assert(actual, expected)` (checkout http://nodejs.org/api/assert.html).

When I changed some of the tests to `assert.deepEqual` they failed.
I will submit a PR to fix the tests.

**Comment by stoeffel** [comment]
The failing test was:
```
1) selectionsort node module should work with sorted arrays:
     AssertionError: [-5,-5,-5,-5,2,2,12,14] deepEqual [-5,1,2,5,12,12,14,16]
```

**Comment by addyosmani** [comment]
Thanks for fixing this!

**Comment by stoeffel** [comment]
No problem :smile:
